name: VulnAlerts

on: 
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: liarsd/VulnAlerts@main
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: done
      run: echo 'done'
